### ISSUE TITLE
Unit testing to-do

### ISSUE THREAD

**Issue by ajrominger** [role-model/roleR#10]
- [ ] death for roleModel
- [ ] speciation for roleModel
- [ ] speciation for rolePhylo

**Comment by ajrominger** [comment]
@ajrominger check Jacob's current tests
